In [2]:
import numpy as np

In [3]:
#lets learn how we can create first dimension array.
a = np.array([1,5,4], dtype="int32")
print(a)

[1 5 4]


In [4]:
#lets learn how we can create two dimension array.
b = np.array([[2.0, 6.0, 7.0 ], [3.0, 7.0, 1.0]])
print(b)

[[2. 6. 7.]
 [3. 7. 1.]]


In [5]:
#lets learn how we can simply know which dimension array we have created.
a.ndim
b.ndim

2

In [6]:
#lets learn how was the shape of our array /get shape
a.shape


(3,)

In [7]:
#lets learn how much memory our numpy arrays take up, 
#get the data type
a.dtype
b.dtype

dtype('float64')

In [8]:
#get the size
a.itemsize
b.itemsize


8

In [9]:
#get the total size
a.nbytes
b.nbytes


48

In [10]:
a = np.array([[11,12,13,14,15,16], [21, 22, 23, 24, 25, 26]])
print(a)

[[11 12 13 14 15 16]
 [21 22 23 24 25 26]]


In [11]:
#getting specific elements, row, coulums, etc.

#1) getting specific element[r, c]
# the meaning of row and column is we simply count and put the exact number of row and column which elemet we want to get.

a[0, 4]

np.int64(15)

In [12]:
# getting specific row
a[0, :]
# so what does it mean it simply means print only the first row and all column on that row.

array([11, 12, 13, 14, 15, 16])

In [13]:
#gertting specific column
a[:, 2]
#it means w ar going to print all the rows but only the one column

array([13, 23])

In [14]:
#Getting a little more fancy [startindex:endindex:stepsize]
a[0,1:6:2]

#this way we can acess elements.

array([12, 14, 16])

In [15]:
#lets learn how we can change the elements specifi element so for that we can simply do it by like this 

print(a[1,4])

#lets change this element 25 for that we do it like this way..

a[1,4] = 10 # what does it means it mean change the the element 25 to 10 

#lets test it even if it was changed or not

print(a[1,4])


25
10


In [16]:
#lets learn how to do changing the elements of entire column up to we want 
#for that we do it like this way 

print(a[:, 3])

#now lets change it
a[:, 3] = [1, 2]
print(a)

[14 24]
[[11 12 13  1 15 16]
 [21 22 23  2 10 26]]


In [17]:
#3-d example 
b = np.array([[[1, 2], [3, 4]], [[5, 6], [7 , 8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [18]:
#Getting specific  element (works outside in )
b[0,1,1]
 


np.int64(4)

In [19]:
#replace
b[:,1,:]= [[9,9], [8, 8]]
print(b)


[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]


In [20]:
#Initializing Different Types of Arrays 

In [21]:
#All 0s matrix
np.zeros(5)



array([0., 0., 0., 0., 0.])

In [22]:
# or we can create different shapes as well like this way,

np.zeros((2,5))

#look we care do it by just simple way like this

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [23]:
#we can create multiple dimessionla as well in simple way 
np.zeros((2,3,4))

#this is the example of 3d

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [24]:
#this is the example of 4-d 
np.zeros((3,2,4,2))

array([[[[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]]]])

In [25]:
#we can also create all 1s matrix as well, like this 
np.ones((2, 3), dtype="int32")

#And we can do all the upper operations which we have done with all 0s matrix
#And we can also specify the data type as well which we have done by using dtype = ""int32

array([[1, 1, 1],
       [1, 1, 1]], dtype=int32)

In [26]:
#Any other number (matrix)
np.full((2,2 ), 99, dtype = "float32")

#this takes two parameters so we gae (2, 2) and 99 
#and we can also specify the data type as well like this dtype = "float32"

array([[99., 99.],
       [99., 99.]], dtype=float32)

In [27]:
#randomd decimal numbers  
np.random.rand(4,2)

array([[0.47095138, 0.25202961],
       [0.31350658, 0.29657681],
       [0.31334291, 0.96731243],
       [0.48126121, 0.93328227]])

In [28]:
#random intigers numbers
np.random.randint(7, size = (3, 3))

array([[4, 5, 5],
       [3, 0, 2],
       [4, 1, 5]], dtype=int32)

In [29]:
#identity matrix 
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [30]:
#range funciton in numpy 
rng = np.arange(12)
print(rng)

#it simple create a a single column with our desire lenght we given as argument

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [31]:
#empty array creation, how we can create empty arrays
empty = np.empty((4, 6))

#it simple create empty arrays and later we can assign our desire element their like this way.

empty



array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [32]:
testingarray = np.array([[1, 2, 3, 4], [4, 3, 2, 1], [5, 6, 7, 8]])
testingarray

array([[1, 2, 3, 4],
       [4, 3, 2, 1],
       [5, 6, 7, 8]])

In [33]:
#we can also use existiant arry to create it empty array by using this (empty_like)

testing = np.empty_like(testingarray)

testing

#so what we have done here is intresting we just assing our one existing array and convert it into empty array.



array([[      2201751742856,                  64,                   0,
                          0],
       [  29555336411086848, 3690200042900500789, 3617063613257691699,
        7090134981002081845],
       [3832675864292700259, 7004331305397860705, 7005405524799273271,
        3763150251488588389]])

In [34]:
#by using .shape we can know which type of arrary we have created. 
testingarray.shape

(3, 4)

In [35]:
#creating a testing arange array 
newtestingarray = np.arange(99)

newtestingarray

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [36]:
#now lets learn how we can replace our exisitng array. for that we have to keep in mind one thing
#that is we can't randomly reshape our array we have to use exact multiple for example if we want to 
#reshape the newtestingarray then we have to use exast multiple which might be (3*33) which is eqal to 
# 99 so we can use (3, 33 ) to reshape this newtestingarry lets learn how we can do it.

newtestingarray = newtestingarray.reshape(3, 33)

newtestingarray


array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [37]:
newtestingarray.ravel()


#So what does it simply make in 1-d array i convert all the element into one line.

#newtestingarray.shape

#so what does the .shape does it simply tell us which shape we are using.

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [47]:
x = [[1, 2, 3], [4, 5, 6 ], [7, 8, 9 ]]

x

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [44]:
ar = np.array(x)
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [42]:
ar.sum(axis=0)

array([12, 15, 18])

In [54]:
#converting our matrix into transvers matrix so for that we have to use .T

ar.T


array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [53]:
ar.flat


In [ ]:
#look we get all the elemnt we use flat for that and acess all the elemnts by using for look.
for item in ar.flat:
    print(item)

1
2
3
4
5
6
7
8
9


In [56]:
ar.ndim

2

In [ ]:
# for right now it shows 9 because our element matrx has total 9 elements.
ar.size

9

In [58]:
#nbytes so it shows the total bites consumed 
#lets see it by one example

ar.nbytes

72

In [61]:
#
one = np.array([1, 2, 4, 454, 5])


In [ ]:
#so what does it do it simply give us the maxium value's position to use for example the maximum value is 
# 454 and that is on 4 th positon so it return 3 
one.argmax()

np.int64(3)

In [ ]:
one.argmin()

#yup just like argmax() but argmin() tell wehere exist our lowest value

np.int64(0)