In [2]:
import numpy as np

In [23]:
#lets learn how we can create first dimension array.
a = np.array([1,5,4], dtype="int32")
print(a)

[1 5 4]


In [13]:
#lets learn how we can create two dimension array.
b = np.array([[2.0, 6.0, 7.0 ], [3.0, 7.0, 1.0]])
print(b)

[[2. 6. 7.]
 [3. 7. 1.]]


In [14]:
#lets learn how we can simply know which dimension array we have created.
a.ndim
b.ndim

2

In [18]:
#lets learn how was the shape of our array /get shape
a.shape


(3,)

In [ ]:
#lets learn how much memory our numpy arrays take up, 
#get the data type
a.dtype
b.dtype

dtype('float64')

In [ ]:
#get the size
a.itemsize
b.itemsize


4

In [ ]:
#get the total size
a.nbytes
b.bbytes


12