In [1]:
import numpy as np

In [2]:
#lets learn how we can create first dimension array.
a = np.array([1,5,4], dtype="int32")
print(a)

[1 5 4]


In [3]:
#lets learn how we can create two dimension array.
b = np.array([[2.0, 6.0, 7.0 ], [3.0, 7.0, 1.0]])
print(b)

[[2. 6. 7.]
 [3. 7. 1.]]


In [4]:
#lets learn how we can simply know which dimension array we have created.
a.ndim
b.ndim

2

In [5]:
#lets learn how was the shape of our array /get shape
a.shape


(3,)

In [6]:
#lets learn how much memory our numpy arrays take up, 
#get the data type
a.dtype
b.dtype

dtype('float64')

In [7]:
#get the size
a.itemsize
b.itemsize


8

In [8]:
#get the total size
a.nbytes
b.nbytes


48

In [9]:
a = np.array([[11,12,13,14,15,16], [21, 22, 23, 24, 25, 26]])
print(a)

[[11 12 13 14 15 16]
 [21 22 23 24 25 26]]


In [10]:
#getting specific elements, row, coulums, etc.

#1) getting specific element[r, c]
# the meaning of row and column is we simply count and put the exact number of row and column which elemet we want to get.

a[0, 4]

np.int64(15)

In [11]:
# getting specific row
a[0, :]
# so what does it mean it simply means print only the first row and all column on that row.

array([11, 12, 13, 14, 15, 16])

In [12]:
#gertting specific column
a[:, 2]
#it means w ar going to print all the rows but only the one column

array([13, 23])

In [13]:
#Getting a little more fancy [startindex:endindex:stepsize]
a[0,1:6:2]

#this way we can acess elements.

array([12, 14, 16])

In [14]:
#lets learn how we can change the elements specifi element so for that we can simply do it by like this 

print(a[1,4])

#lets change this element 25 for that we do it like this way..

a[1,4] = 10 # what does it means it mean change the the element 25 to 10 

#lets test it even if it was changed or not

print(a[1,4])


25
10


In [15]:
#lets learn how to do changing the elements of entire column up to we want 
#for that we do it like this way 

print(a[:, 3])

#now lets change it
a[:, 3] = [1, 2]
print(a)

[14 24]
[[11 12 13  1 15 16]
 [21 22 23  2 10 26]]


In [16]:
#3-d example 
b = np.array([[[1, 2], [3, 4]], [[5, 6], [7 , 8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [22]:
#Getting specific  element (works outside in )
b[0,1,1]
 


np.int64(4)

In [24]:
#replace
b[:,1,:]= [[9,9], [8, 8]]
print(b)


[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]


In [25]:
#Initializing Different Types of Arrays 

In [31]:
#All 0s matrix
np.zeros(5)



array([0., 0., 0., 0., 0.])

In [ ]:
# or we can create different shapes as well like this way,

np.zeros((2,5))

#look we care do it by just simple way like this

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
#we can create multiple dimessionla as well in simple way 
np.zeros((2,3,4))

#this is the example of 3d

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [33]:
#this is the example of 4-d 
np.zeros((3,2,4,2))

array([[[[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]]]])

In [ ]:
#we can also create all 1s matrix as well, like this 
np.ones((2, 3), dtype="int32")

#And we can do all the upper operations which we have done with all 0s matrix
#And we can also specify the data type as well which we have done by using dtype = ""int32

array([[1, 1, 1],
       [1, 1, 1]], dtype=int32)

In [ ]:
#Any other number (matrix)
np.full((2,2 ), 99, dtype = "float32")

#this takes two parameters so we gae (2, 2) and 99 
#and we can also specify the data type as well like this dtype = "float32"

array([[99, 99],
       [99, 99]])