In [2]:
import numpy as np

In [3]:
#lets learn how we can create first dimension array.
a = np.array([1,5,4], dtype="int32")
print(a)

[1 5 4]


In [4]:
#lets learn how we can create two dimension array.
b = np.array([[2.0, 6.0, 7.0 ], [3.0, 7.0, 1.0]])
print(b)

[[2. 6. 7.]
 [3. 7. 1.]]


In [5]:
#lets learn how we can simply know which dimension array we have created.
a.ndim
b.ndim

2

In [6]:
#lets learn how was the shape of our array /get shape
a.shape


(3,)

In [7]:
#lets learn how much memory our numpy arrays take up, 
#get the data type
a.dtype
b.dtype

dtype('float64')

In [8]:
#get the size
a.itemsize
b.itemsize


8

In [10]:
#get the total size
a.nbytes
b.nbytes


48

In [ ]:
a = np.array([[11,12,13,14,15,16], [21, 22, 23, 24, 25, 26]])
print(a)

[[11 12 13 14 15 16]
 [21 22 23 24 25 26]
 [31 32 33 34 35 36]]


In [ ]:
#getting specific elements, row, coulums, etc.

#1) getting specific element[r, c]
# the meaning of row and column is we simply count and put the exact number of row and column which elemet we want to get.



2